### ISSUE TITLE
Vectorblade V1.13

### ISSUE THREAD

**Issue by coolfox89** [malbanGit/Vectorblade#1]
How do I build Vectorblade V1.13 with Vide? Do you have instructions on how to do this?

**Comment by malbanGit** [comment]
Download the git repo.
Start Vide.
Load the project file "[Vectorblade4BankProjectProperty.xml]" in the editor.
Press the compile btton.

**Comment by coolfox89** [comment]
I cannot get the game to work. I must be doing something wrong? I open Vide then choose Tools and open Vedi. Then I click open file and choose Vectorblade4BankProjectProperty.xml. Then I click assemble current file. I get five bin files called, mainBank0_0.bin, mainBank1_1.bin, mainBank2_2.bin, mainBank3_3.bin, and mainBank0_256k.bin. I tried opening these bins on a Vectrex emulator called ParaJVE. It shows the initial bootup screen that says Vectorblade  Version 1.13 and then it brings up an error screen. I tested your preassembled alpha version, and it loaded up and played just fine so something must be wrong about how I'm assembling the game.

**Comment by malbanGit** [comment]
No - You did everything fine - it is just, that ParaJVE can not run Vectorblade.
It is a 4 Bank (switching) game, which ParaJVE does not support.

The alpha version is a 2 Bank game - which ParaJVE does support.
If you want to play it in with an emulator - use Vide. I think the online emulator (DrSnuggles) also plays it.
If you want to use RetroArch - then you should use my core (see on my link page the sources).

I don't think any other emulator is able to play Vectorblade.

**Comment by malbanGit** [comment]
I am closing this ticket, since it appears to be no fault on my part. 
Feel free to open other tickets, if you have other issues.
